# coding: utf-8

# DO NOT EDIT
# Autogenerated from the notebook categorical_interaction_plot.ipynb.
# Edit the notebook and then sync the output with this file.
#
# flake8: noqa
# DO NOT EDIT

# # 绘制类别因子的交互作用

# 在此示例中，我们将类别因子之间的交互作用进行可视化。 首先，我们将创建一些
# 已初始化的分类数据。 然后使用 interaction_plot 函数进行绘制，该函数将
#  x-因子 类别重新编码为整数。

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from statsmodels.graphics.factorplots import interaction_plot

np.random.seed(12345)
weight = pd.Series(np.repeat(['low', 'hi', 'low', 'hi'], 15), name='weight')
nutrition = pd.Series(np.repeat(['lo_carb', 'hi_carb'], 30), name='nutrition')
days = np.log(np.random.randint(1, 30, size=60))

fig, ax = plt.subplots(figsize=(6, 6))
fig = interaction_plot(
    x=weight,
    trace=nutrition,
    response=days,
    colors=['red', 'blue'],
    markers=['D', '^'],
    ms=10,
    ax=ax)
