# coding: utf-8

# DO NOT EDIT
# Autogenerated from the notebook markov_regression.ipynb.
# Edit the notebook and then sync the output with this file.
#
# flake8: noqa
# DO NOT EDIT

# ## Markov 切换动态回归模型

# 这个笔记提供了一个在 statsmodels 中使用 Markov 切换模型来估计政权变化的动态回归模型的示例。 
# 它遵循 Stata 的 Markov切换模型文档中的示例，该文档可在http://www.stata.com/manuals14/tsmswitch.pdf上找到。


import numpy as np
import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt

# NBER 经济衰退
from pandas_datareader.data import DataReader
from datetime import datetime
usrec = DataReader(
    'USREC', 'fred', start=datetime(1947, 1, 1), end=datetime(2013, 4, 1))

# ### 带有转换截距的联邦基金利率
# 第一个示例将联邦基金利率建模为固定截距周围的噪声，但截距在不同政权下会发生变化。 该模型很简单：
#
# $$r_t = \mu_{S_t} + \varepsilon_t \qquad \varepsilon_t \sim N(0,
# \sigma^2)$$
#
# 其中 $S_t \in \{0, 1\}$, 且政权转换依据
#
# $$ P(S_t = s_t | S_{t-1} = s_{t-1}) =
# \begin{bmatrix}
# p_{00} & p_{10} \\
# 1 - p_{00} & 1 - p_{10}
# \end{bmatrix}
# $$
#
# 我们将通过极大似然来估计这个模型的参数: $p_{00}, p_{10}, \mu_0, \mu_1, \sigma^2$.
#
# 可在 https://www.stata-press.com/data/r14/usmacro 中找到这个示例使用的数据

# Get the federal funds rate data
from statsmodels.tsa.regime_switching.tests.test_markov_regression import fedfunds
dta_fedfunds = pd.Series(
    fedfunds, index=pd.date_range('1954-07-01', '2010-10-01', freq='QS'))

# 绘图
dta_fedfunds.plot(title='Federal funds rate', figsize=(12, 3))

# 拟合模型
# (切换均值是 MarkovRegession 模型的默认值)
mod_fedfunds = sm.tsa.MarkovRegression(dta_fedfunds, k_regimes=2)
res_fedfunds = mod_fedfunds.fit()

res_fedfunds.summary()

# 从 summary 的输出来看，第一个政权（“低政权”）的平均联邦资金利率估计为3.7美元，而在“高政权”中为9.6美元。 
# 下面我们绘制处于高政权的平滑概率。 该模型表明，1980 年代是联邦基金利率高企的时期。


res_fedfunds.smoothed_marginal_probabilities[1].plot(
    title='Probability of being in the high regime', figsize=(12, 3))

# 从估计的过渡矩阵中，我们可以计算出低状态与高状态的预期持续时间。

print(res_fedfunds.expected_durations)

# 弱势政权预计将持续约十四年，而强势政权预计将仅持续约五年。

# ### 带有切换截距且滞后因变量的联邦基金利率
#
# 第二个示例扩展了之前的模型，包括滞后值的联邦基金利率。
#
# $$r_t = \mu_{S_t} + r_{t-1} \beta_{S_t} + \varepsilon_t \qquad
# \varepsilon_t \sim N(0, \sigma^2)$$
#
# 其中 $S_t \in \{0, 1\}$, 且政权转换依据
#
# $$ P(S_t = s_t | S_{t-1} = s_{t-1}) =
# \begin{bmatrix}
# p_{00} & p_{10} \\
# 1 - p_{00} & 1 - p_{10}
# \end{bmatrix}
# $$
#
# 我们将通过极大似然来估计这个模型的参数: $p_{00}, p_{10}, \mu_0, \mu_1, \beta_0, \beta_1, \sigma^2$.

# 拟合模型
mod_fedfunds2 = sm.tsa.MarkovRegression(
    dta_fedfunds.iloc[1:], k_regimes=2, exog=dta_fedfunds.iloc[:-1])
res_fedfunds2 = mod_fedfunds2.fit()

res_fedfunds2.summary()

# summary 输出的几个注意事项:
#
# 1.信息标准已大大降低，表明此模型比以前的模型更适合。
# 2.政权的解释是截距切换。 现在，第一个政权的截距较高，第二个政权的截距较低。
#
# 检查“高政权”的平滑概率，我们现在看到更多的可变性。

res_fedfunds2.smoothed_marginal_probabilities[0].plot(
    title='Probability of being in the high regime', figsize=(12, 3))

# 最后，每个政权的预期持续时间已大大减少。

print(res_fedfunds2.expected_durations)

# ### 具有2 或 3 政权的 Taylor 规则
#
# 现在，包括两个附加的外生变量-一个输出差异度量和一个通货膨胀的度量——估计具有 2 和 3 政权转换 Taylor 规则，看看哪个更好的拟合了数据。

# 由于模型通常难以估计，因此对于3 政权模型，我们对初始参数进行搜索以改善效果，并指定 20 个随机搜索重复。


# 获取其他数据
from statsmodels.tsa.regime_switching.tests.test_markov_regression import ogap, inf
dta_ogap = pd.Series(
    ogap, index=pd.date_range('1954-07-01', '2010-10-01', freq='QS'))
dta_inf = pd.Series(
    inf, index=pd.date_range('1954-07-01', '2010-10-01', freq='QS'))

exog = pd.concat((dta_fedfunds.shift(), dta_ogap, dta_inf), axis=1).iloc[4:]

# 拟合 2-regime 模型
mod_fedfunds3 = sm.tsa.MarkovRegression(
    dta_fedfunds.iloc[4:], k_regimes=2, exog=exog)
res_fedfunds3 = mod_fedfunds3.fit()

# 拟合 3-regime 模型
np.random.seed(12345)
mod_fedfunds4 = sm.tsa.MarkovRegression(
    dta_fedfunds.iloc[4:], k_regimes=3, exog=exog)
res_fedfunds4 = mod_fedfunds4.fit(search_reps=20)

res_fedfunds3.summary()

res_fedfunds4.summary()

# 由于较低的信息标准，我们可能更喜欢 3-state 模型，可以解释低，中和高利率政权。
# 每个政权的平滑概率如下图所示。


fig, axes = plt.subplots(3, figsize=(10, 7))

ax = axes[0]
ax.plot(res_fedfunds4.smoothed_marginal_probabilities[0])
ax.set(title='Smoothed probability of a low-interest rate regime')

ax = axes[1]
ax.plot(res_fedfunds4.smoothed_marginal_probabilities[1])
ax.set(title='Smoothed probability of a medium-interest rate regime')

ax = axes[2]
ax.plot(res_fedfunds4.smoothed_marginal_probabilities[2])
ax.set(title='Smoothed probability of a high-interest rate regime')

fig.tight_layout()

# ### 切换方差
#
# 我们也可以允许切换方差，特别是，我们认为模型是
#
# $$
# y_t = \mu_{S_t} + y_{t-1} \beta_{S_t} + \varepsilon_t \quad
# \varepsilon_t \sim N(0, \sigma_{S_t}^2)
# $$
#
# 我们将通过极大似然来估计这个模型的参数:
# $p_{00}, p_{10}, \mu_0, \mu_1, \beta_0, \beta_1, \sigma_0^2, \sigma_1^2$.
#
# 这个方案是股票的绝对收益，我们可以在 https://www.stata-press.com/data/r14/snp500 找到数据。

# 获取联邦基金利率数据
from statsmodels.tsa.regime_switching.tests.test_markov_regression import areturns
dta_areturns = pd.Series(
    areturns, index=pd.date_range('2004-05-04', '2014-5-03', freq='W'))

# 绘图
dta_areturns.plot(title='Absolute returns, S&P500', figsize=(12, 3))

# 拟合模型
mod_areturns = sm.tsa.MarkovRegression(
    dta_areturns.iloc[1:],
    k_regimes=2,
    exog=dta_areturns.iloc[:-1],
    switching_variance=True)
res_areturns = mod_areturns.fit()

res_areturns.summary()

# 第一方案是低方差方案，第二方案是高方差方案。下面我们绘制了处于低方差政权的概率。 在2008年至2012年之间，
# 似乎没有明显迹象表明有一个政权可以指导经济。


res_areturns.smoothed_marginal_probabilities[0].plot(
    title='Probability of being in a low-variance regime', figsize=(12, 3))
