# coding: utf-8

# DO NOT EDIT
# Autogenerated from the notebook tsa_arma_1.ipynb.
# Edit the notebook and then sync the output with this file.
#
# flake8: noqa
# DO NOT EDIT

# # 自回归移动平均值（ARMA）：人工数据

import numpy as np
import statsmodels.api as sm
import pandas as pd
from statsmodels.tsa.arima_process import arma_generate_sample
np.random.seed(12345)

# 从ARMA进程生成一些数据：

arparams = np.array([.75, -.25])
maparams = np.array([.65, .35])

# arma_generate 函数的约定要求我们为AR和MA参数的零延迟指定一个1，并否定AR参数。

arparams = np.r_[1, -arparams]
maparams = np.r_[1, maparams]
nobs = 250
y = arma_generate_sample(arparams, maparams, nobs)

#  现在，可选地，我们可以添加一些日期信息。 在此示例中，我们将使用 pandas 时间序列。


dates = sm.tsa.datetools.dates_from_range('1980m1', length=nobs)
y = pd.Series(y, index=dates)
arma_mod = sm.tsa.ARMA(y, order=(2, 2))
arma_res = arma_mod.fit(trend='nc', disp=-1)

print(arma_res.summary())

y.tail()

import matplotlib.pyplot as plt
fig, ax = plt.subplots(figsize=(10, 8))
fig = arma_res.plot_predict(start='1999-06-30', end='2001-05-31', ax=ax)
legend = ax.legend(loc='upper left')
